#!/bin/bash
set -e

[ -f .ruby-version ] &&
  export RBENV_VERSION=$(cat .ruby-version)

[ -f .app-config/production.sh ] &&
  . .app-config/production.sh

export PATH=/usr/share/rbenv/shims:$PATH
bundle install --local
